version: '3'

tasks:
  setup-mac-buildkite:
    desc: Install the mac-mini Buildkite token and SSH config via nix develop
    cmds:
      - nix develop -c mac-mini-buildkite-install-token
      - nix develop -c mac-mini-buildkite-install-ssh
