{ writeShellScriptBin }:
writeShellScriptBin "mac-mini-buildkite-install-ssh" ''
  set -euo pipefail

  AGENT_USER=buildkite-agent-macos
  AGENT_HOME=/private/var/lib/$AGENT_USER
  # The invoking user's ssh config. Override for testing or non-standard layouts.
  USER_SSH_CONFIG=''${USER_SSH_CONFIG:-$HOME/.ssh/config}
  USER_SSH_KNOWN_HOSTS=''${USER_SSH_KNOWN_HOSTS:-$HOME/.ssh/known_hosts}
  ORIGIN_HOST_KEY='origin.cursor.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFaMKo6HCtmngBwlSH2ATs8+A6eTr+cCON5RKZX/3/MO'

  die() { echo "error: $*" >&2; exit 1; }

  [[ "$(hostname -s)" == "mac-mini" ]] \
    || die "run on mac-mini only (hostname is $(hostname -s))"

  dscl . -read /Users/$AGENT_USER >/dev/null 2>&1 \
    || die "user $AGENT_USER does not exist — run: darwin-rebuild switch --flake .#mac-mini"

  [[ -f "$USER_SSH_CONFIG" ]] \
    || die "$USER_SSH_CONFIG not found"

  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' EXIT

  # Extract Host blocks whose patterns mention github.com or origin.cursor.com.
  extracted=$tmp/ssh_config_extracted
  awk '
    /^[[:space:]]*Host[[:space:]]+/ {
      if (in_block && block_wanted) { printf "%s", block }
      block = $0 "\n"
      in_block = 1
      block_wanted = 0
      for (i = 2; i <= NF; i++) {
        if ($i ~ /github\.com/ || $i ~ /origin\.cursor\.com/) {
          block_wanted = 1
        }
      }
      next
    }
    {
      if (in_block) { block = block $0 "\n" }
    }
    END {
      if (in_block && block_wanted) { printf "%s", block }
    }
  ' "$USER_SSH_CONFIG" > "$extracted"

  [[ -s "$extracted" ]] \
    || die "no Host block for github.com or origin.cursor.com found in $USER_SSH_CONFIG"

  header=$tmp/header
  cat > "$header" <<'EOF'
# Generated by mac-mini-buildkite-install-ssh
# Copied from the invoking user's ~/.ssh/config for the Buildkite agent user.
EOF

  # Ensure the agent .ssh directory exists before copying keys.
  sudo mkdir -p "$AGENT_HOME/.ssh"
  sudo chmod 700 "$AGENT_HOME/.ssh"
  sudo chown "$AGENT_USER:$AGENT_USER" "$AGENT_HOME/.ssh"

  config_out=$tmp/config
  cat "$header" > "$config_out"

  # Copy the relevant Host blocks into the agent config, copying referenced
  # private keys into the agent home and rewriting their IdentityFile paths
  # to ~/.ssh/<basename>. Skip AddKeysToAgent/UseKeychain, which don't apply
  # to the non-interactive buildkite-agent user.
  while IFS= read -r line; do
    if printf '%s\n' "$line" | grep -qE '^[[:space:]]*(AddKeysToAgent|UseKeychain)[[:space:]]+'; then
      continue
    fi

    if printf '%s\n' "$line" | grep -qE '^[[:space:]]*IdentityFile[[:space:]]+'; then
      src=$(printf '%s\n' "$line" | sed -E 's/^[[:space:]]*IdentityFile[[:space:]]+//')
      # Expand a leading '~' to the invoking user's HOME.
      src="''${src/#\~/$HOME}"
      fname=$(basename "$src")

      if [[ -f "$src" ]]; then
        sudo install -m 600 -o "$AGENT_USER" -g "$AGENT_USER" "$src" "$AGENT_HOME/.ssh/$fname"
        if [[ -f "$src.pub" ]]; then
          sudo install -m 644 -o "$AGENT_USER" -g "$AGENT_USER" "$src.pub" "$AGENT_HOME/.ssh/$fname.pub"
        fi
        # Rewrite the path so it resolves inside the agent home.
        printf '    IdentityFile ~/.ssh/%s\n' "$fname" >> "$config_out"
      else
        echo "warning: IdentityFile $src not found; copying line unchanged" >&2
        printf '%s\n' "$line" >> "$config_out"
      fi
    else
      printf '%s\n' "$line" >> "$config_out"
    fi
  done < "$extracted"

  # Build a minimal known_hosts for the agent from the invoking user's file.
  # Origin's key is pinned below as a fallback; GitHub keys are copied from
  # the host so the agent can verify github.com (public keys only).
  known=$tmp/known_hosts
  : > "$known"

  extract_known_host() {
    local host=$1
    local file=$2
    [[ -f "$file" ]] || return 0
    ssh-keygen -F "$host" -f "$file" 2>/dev/null \
      | sed -e '/^[[:space:]]*$/d' -e '/^#[[:space:]]*[Hh]ost /d' >> "$known" || true
  }

  extract_known_host github.com "$USER_SSH_KNOWN_HOSTS"
  extract_known_host origin.cursor.com "$USER_SSH_KNOWN_HOSTS"

  # Ensure origin's key is present even if the host file lacks it.
  if ! grep -qF "origin.cursor.com" "$known" 2>/dev/null; then
    printf '%s\n' "$ORIGIN_HOST_KEY" >> "$known"
  fi

  sudo install -m 644 -o "$AGENT_USER" -g "$AGENT_USER" "$config_out" "$AGENT_HOME/.ssh/config"
  sudo install -m 644 -o "$AGENT_USER" -g "$AGENT_USER" "$known" "$AGENT_HOME/.ssh/known_hosts"

  echo "Installed agent SSH configuration and keys:"
  echo "  $AGENT_HOME/.ssh/config"
  echo "  $AGENT_HOME/.ssh/known_hosts"
  ls -l "$AGENT_HOME/.ssh"/*
  echo
  echo "The Buildkite launchd job runs with HOME=$AGENT_HOME and no GIT_SSH_COMMAND,"
  echo "so git/ssh will use the per-domain Host blocks above."
  echo
  echo "Verify as the agent (agent shell is /usr/bin/false — exec ssh/git directly):"
  echo "  sudo -u $AGENT_USER -H ssh -o BatchMode=yes -T git@github.com"
  echo "  sudo -u $AGENT_USER -H ssh -o BatchMode=yes -T git@origin.cursor.com"
  echo "  sudo -u $AGENT_USER -H git ls-remote git@github.com:<org>/<repo>.git HEAD"
  echo "  sudo -u $AGENT_USER -H git ls-remote https://origin.cursor.com/git/<owner>/<repo>.git HEAD"
''
