steps:
  - label: ":nix: flake check"
    key: flake-check
    if: |
      build.branch == "develop" || build.branch == "main" ||
      build.pull_request.base_branch == "develop" ||
      build.pull_request.base_branch == "main"
    command: .buildkite/scripts/flake-check.sh
    plugins:
      - docker#v5.14.0:
          image: "nixos/nix:2.28.2"
          mount-checkout: true
          propagate-environment: true
          environment:
            - "NIX_CONFIG=experimental-features = nix-command flakes"
    agents:
      queue: linux-medium
    timeout_in_minutes: 90
    retry:
      automatic:
        - exit_status: "*"
          limit: 1

  - label: ":nix: flake check (mac-mini aarch64-linux)"
    key: flake-check-mac-mini-linux
    if: |
      build.branch == "develop" || build.branch == "main" ||
      build.pull_request.base_branch == "develop" ||
      build.pull_request.base_branch == "main"
    command: .buildkite/scripts/flake-check.sh
    agents:
      queue: mac-mini-aarch64-linux
    timeout_in_minutes: 90

  - label: ":nix: flake check (mac-mini macos)"
    key: flake-check-mac-mini-macos
    if: |
      build.branch == "develop" || build.branch == "main" ||
      build.pull_request.base_branch == "develop" ||
      build.pull_request.base_branch == "main"
    command: .buildkite/scripts/flake-check.sh
    agents:
      queue: mac-mini-macos
    timeout_in_minutes: 90
